
name: Linter

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    env: 
      DEBIAN_FRONTEND: noninteractive

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get update && apt-get install -y ca-certificates curl golang-go libwayland-dev libxkbcommon-dev mesa-common-dev libglu1-mesa-dev libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
    
    - name: Install go deps
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.5

    - name: Linting
      run: $(go env GOPATH)/bin/golangci-lint run
    