
name: UnitTesting

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Unit Test
      run: go test -v
    
    - name: Show Coverage
      run: go test -coverprofile cover.out && cat cover.out
